const API='https://kmjdujjdtrlnggyjokbb.supabase.co/functions/v1/tripbuy-api';
const API_KEY='sb_publishable_YikgBFZAz0Lyewzq5CT2Eg_f48UoKXR';
const STATUS=['收到委託','資訊確認','已排入採買','現場尋找','已買到','缺貨','跳過','已取消','待結算','已付款','已交付'];
const app={role:null,person:null,settings:null,requests:[],people:[],editId:null,editImagePath:null};
let sessionToken=localStorage.getItem('tripbuy_session')||'';

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const yen=n=>'¥'+Number(n||0).toLocaleString('ja-JP');
const twd=n=>'NT$'+Math.round(Number(n||0)).toLocaleString('zh-TW');
function safeUrl(v){try{const u=new URL(String(v||''));return ['http:','https:'].includes(u.protocol)?u.href:''}catch(_){return ''}}
function showLoading(v=true){$('loading').classList.toggle('hidden',!v)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
async function api(action,payload={}){const headers={'Content-Type':'application/json','apikey':API_KEY};if(sessionToken)headers['x-tripbuy-session']=sessionToken;const r=await fetch(API,{method:'POST',headers,body:JSON.stringify({action,...payload})});let d={};try{d=await r.json()}catch(_){d={error:'伺服器回應格式錯誤'}}if(!r.ok)throw new Error(d.error||`連線失敗 (${r.status})`);return d}
function setSession(token,role){sessionToken=token||'';if(token)localStorage.setItem('tripbuy_session',token);else localStorage.removeItem('tripbuy_session');if(role)localStorage.setItem('tripbuy_role',role);else localStorage.removeItem('tripbuy_role')}
function applySettings(s){if(!s)return;app.settings=s;$('tripTitle').textContent=s.trip_name||'日本代買旅行';$('routeNote').textContent=s.route_note||'行程待更新';$('registrationStamp').innerHTML=s.registration_open?'OPEN<br>收單中':'CLOSED<br>已收單';$('registrationStamp').style.borderColor=s.registration_open?'var(--green)':'var(--red)';$('registrationStamp').style.color=s.registration_open?'var(--green)':'var(--red)';$('cutoffText').textContent=s.order_cutoff?`收單截止：${s.order_cutoff}`:''}
function switchAuth(mode){['register','login','admin'].forEach(x=>{$(`tab-${x}`).classList.toggle('active',x===mode);$(`auth-${x}`).classList.toggle('active',x===mode)});if(mode==='admin')$('adminPassword').focus()}
function scrollAuth(){setTimeout(()=>$('authScreen').scrollIntoView({behavior:'smooth',block:'start'}),50)}
function badge(status){let cls='wait';if(['已排入採買','現場尋找','待結算'].includes(status))cls='go';if(['已買到','已付款','已交付'].includes(status))cls='done';if(['缺貨','跳過','已取消'].includes(status))cls='bad';return `<span class="badge ${cls}">${esc(status)}</span>`}
function personName(id){const p=app.people.find(x=>x.id===id);return p?.display_name||'未知朋友'}
function rate(){return Number(app.settings?.exchange_rate||0.22)}
function requestTwd(r){return Math.round(Number(r.actual_yen||0)*rate())}
function payableRequests(list){return list.filter(r=>!['缺貨','跳過','已取消'].includes(r.status))}

async function init(){try{const p=await api('public_settings');applySettings(p.settings)}catch(e){toast(e.message)}const u=new URLSearchParams(location.search).get('u');if(u){$('loginId').value=u.toUpperCase();switchAuth('login')}if(sessionToken){try{const s=await api('session');app.role=s.role;app.person=s.person;applySettings(s.settings);if(app.role==='friend')await loadMine(false);else await loadAdmin(false);enterApp();return}catch(_){setSession('',null)}}showGuest();showLoading(false)}
function showGuest(){app.role=null;app.person=null;$('authScreen').classList.remove('hidden');$('appScreen').classList.add('hidden');$('mobileNav').classList.add('hidden');$('userPill').classList.add('hidden');$('logoutBtn').classList.add('hidden');$('adminGuestBtn').classList.remove('hidden');$('guestCta').classList.remove('hidden');$('memberCta').classList.add('hidden')}
function enterApp(){ $('authScreen').classList.add('hidden');$('appScreen').classList.remove('hidden');$('mobileNav').classList.remove('hidden');$('userPill').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('adminGuestBtn').classList.add('hidden');$('guestCta').classList.add('hidden');$('memberCta').classList.remove('hidden');if(app.role==='friend'){$('avatar').textContent=(app.person?.display_name||'友').slice(0,1);$('userName').textContent=app.person?.display_name||'朋友';$('userSub').textContent=app.person?.public_id||'';renderFriend();buildNav('friend');showView('overview',false)}else{$('avatar').textContent='管';$('userName').textContent='管理員';$('userSub').textContent='OWNER MODE';renderAdmin();buildNav('admin');showView('adminHome',false)}showLoading(false)}
function buildNav(role){const friend=[['overview','總覽','⌂'],['new','新增委託','＋'],['mine','我的委託','🧾'],['account','專屬入口','🔐']];const admin=[['adminHome','總覽','⌂'],['adminBoard','採買看板','📍'],['adminOrders','全部委託','🧾'],['adminPeople','依朋友','👥'],['adminSettings','設定','⚙️']];const items=role==='admin'?admin:friend;$('sideNav').innerHTML=items.map((x,i)=>`<button data-view="${x[0]}" onclick="showView('${x[0]}')">${x[2]} ${x[1]} <span>${String(i+1).padStart(2,'0')}</span></button>`).join('');const mobile=(role==='admin'?admin.slice(0,4):friend);$('mobileNav').style.gridTemplateColumns=`repeat(${mobile.length},1fr)`;$('mobileNav').innerHTML=mobile.map(x=>`<button data-view="${x[0]}" onclick="showView('${x[0]}')"><span>${x[2]}</span>${x[1]}</button>`).join('')}
function showView(id,scroll=true){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='mine'&&app.role==='friend')renderMine();if(id==='adminBoard'&&app.role==='admin')renderShopBoard();if(id==='adminPeople'&&app.role==='admin')renderPeople();if(scroll)window.scrollTo({top:$('appScreen').offsetTop-8,behavior:'smooth'})}

async function registerFriend(){const name=$('regName').value.trim(),line=$('regLine').value.trim(),pin=$('regPin').value.trim();if(!name)return toast('請填姓名或暱稱');if(!/^\d{4}$/.test(pin))return toast('PIN 請設定為 4 位數字');showLoading(true);try{const d=await api('register_friend',{display_name:name,line_name:line,pin});setSession(d.session.token,'friend');app.role='friend';app.person=d.person;applySettings(d.settings);localStorage.setItem('tripbuy_public_id',d.person.public_id);app.requests=[];enterApp();toast(`建立完成！你的專屬 ID：${d.person.public_id}`)}catch(e){toast(e.message);showLoading(false)}}
async function friendLogin(){const id=$('loginId').value.trim().toUpperCase(),pin=$('loginPin').value.trim();if(!id||!/^\d{4}$/.test(pin))return toast('請輸入專屬 ID 與 4 位 PIN');showLoading(true);try{const d=await api('friend_login',{public_id:id,pin});setSession(d.session.token,'friend');app.role='friend';app.person=d.person;applySettings(d.settings);localStorage.setItem('tripbuy_public_id',d.person.public_id);await loadMine(false);enterApp()}catch(e){toast(e.message);showLoading(false)}}
async function adminLogin(){const password=$('adminPassword').value;if(!password)return toast('請輸入管理員密碼');showLoading(true);try{const d=await api('admin_login',{password});setSession(d.session.token,'admin');app.role='admin';app.person=null;applySettings(d.settings);await loadAdmin(false);enterApp()}catch(e){toast(e.message);showLoading(false)}}
async function logout(){try{await api('logout')}catch(_){}setSession('',null);app.role=null;app.person=null;app.requests=[];app.people=[];showGuest();switchAuth('login');toast('已登出')}

async function loadMine(repaint=true){const d=await api('list_my_requests');app.requests=d.requests||[];app.person=d.person;applySettings(d.settings);if(repaint)renderFriend()}
function renderFriend(){const active=payableRequests(app.requests);const purchased=active.filter(r=>Number(r.actual_yen)>0);const totalYen=purchased.reduce((s,r)=>s+Number(r.actual_yen||0),0);$('helloTitle').textContent=`${app.person?.display_name||'你'}的代買清單`;$('friendStats').innerHTML=`<div class="stat"><small>全部委託</small><b>${app.requests.length}</b></div><div class="stat"><small>採買中</small><b>${active.filter(r=>['已排入採買','現場尋找'].includes(r.status)).length}</b></div><div class="stat"><small>已買到</small><b>${active.filter(r=>r.status==='已買到'||r.status==='待結算'||r.status==='已付款'||r.status==='已交付').length}</b></div><div class="stat"><small>目前實付</small><b>${yen(totalYen)}</b><span class="tiny muted">≈ ${twd(totalYen*rate())}</span></div>`;renderRecent();renderMine();$('accountId').value=app.person?.public_id||'';$('personalUrl').value=`https://tripbuy-log.vercel.app/?u=${encodeURIComponent(app.person?.public_id||'')}`}
function requestCard(r){const canEdit=['收到委託','資訊確認'].includes(r.status),canCancel=['收到委託','資訊確認','已排入採買'].includes(r.status);const img=r.image_url?`<img class="thumb" src="${esc(r.image_url)}" alt="商品圖">`:`<div class="thumb empty">🛍️</div>`;const price=r.actual_yen>0?`<b>${yen(r.actual_yen)}</b><span>≈ ${twd(requestTwd(r))}</span>`:r.estimated_yen>0?`<b>${yen(r.estimated_yen)}</b><span>預估</span>`:`<b>待確認</b><span>預算 ${r.budget_twd?esc(twd(r.budget_twd)):'未填'}</span>`;return `<div class="request-card">${img}<div><h3>${esc(r.product_name)} ×${r.qty}</h3><div class="meta">${esc(r.store_name||'店家待確認')} · ${esc(r.spec||'規格未填')}</div><div style="margin-top:8px">${badge(r.status)}</div><div class="card-actions">${safeUrl(r.product_url)?`<a class="btn line small" href="${esc(safeUrl(r.product_url))}" target="_blank" rel="noopener">開啟連結</a>`:''}${canEdit?`<button class="btn line small" onclick="editRequest('${r.id}')">修改</button>`:''}${canCancel?`<button class="btn red small" onclick="cancelRequest('${r.id}')">取消</button>`:''}</div></div><div class="money">${price}</div></div>`}
function renderRecent(){const box=$('recentList');const rows=app.requests.slice(0,3);box.innerHTML=rows.length?rows.map(requestCard).join(''):`<div class="empty-state">還沒有代買委託。<br><button class="btn green" style="margin-top:12px" onclick="showView('new')">新增第一筆</button></div>`}
function renderMine(){const box=$('myList');box.innerHTML=app.requests.length?app.requests.map(requestCard).join(''):`<div class="empty-state">目前沒有委託紀錄。</div>`}
function previewImage(){const f=$('fImage').files[0];if(!f)return removeImage();if(f.size>4*1024*1024){$('fImage').value='';return toast('圖片不可超過 4MB')}const rd=new FileReader();rd.onload=()=>{$('previewImg').src=rd.result;$('imagePreview').classList.remove('hidden')};rd.readAsDataURL(f)}
function removeImage(){$('fImage').value='';$('previewImg').removeAttribute('src');$('imagePreview').classList.add('hidden');if(app.editId)app.editImagePath=null}
function formPayload(){return{product_name:$('fName').value.trim(),product_url:$('fUrl').value.trim(),qty:Number($('fQty').value||1),budget_twd:Number($('fBudget').value||0),store_name:$('fStore').value.trim(),spec:$('fSpec').value.trim(),substitute_policy:$('fAlt').value,note:$('fNote').value.trim(),image_path:app.editImagePath||''}}
async function fileDataUrl(file){return await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function saveRequest(){const payload=formPayload();if(!payload.product_name)return toast('請填商品名稱');const wasEdit=!!app.editId;showLoading(true);try{const file=$('fImage').files[0];if(file){const up=await api('upload_image',{data_url:await fileDataUrl(file)});payload.image_path=up.image_path}if(app.editId)await api('update_request',{id:app.editId,...payload});else await api('create_request',payload);await loadMine(false);resetRequestForm();renderFriend();showView('mine',false);toast(wasEdit?'委託已更新':'委託已送出')}catch(e){toast(e.message)}finally{showLoading(false)}}
function editRequest(id){const r=app.requests.find(x=>x.id===id);if(!r)return;app.editId=id;app.editImagePath=r.image_path||null;$('fName').value=r.product_name||'';$('fUrl').value=r.product_url||'';$('fQty').value=r.qty||1;$('fBudget').value=r.budget_twd||'';$('fStore').value=r.store_name||'';$('fSpec').value=r.spec||'';$('fAlt').value=r.substitute_policy||'不要買';$('fNote').value=r.note||'';$('formTitle').textContent='修改代買委託';$('submitRequestBtn').textContent='儲存修改';$('editWarning').classList.remove('hidden');if(r.image_url){$('previewImg').src=r.image_url;$('imagePreview').classList.remove('hidden')}else $('imagePreview').classList.add('hidden');showView('new')}
function resetRequestForm(){app.editId=null;app.editImagePath=null;['fName','fUrl','fBudget','fStore','fSpec','fNote'].forEach(id=>$(id).value='');$('fQty').value=1;$('fAlt').value='不要買';$('fImage').value='';$('imagePreview').classList.add('hidden');$('formTitle').textContent='新增代買委託';$('submitRequestBtn').textContent='送出委託';$('editWarning').classList.add('hidden')}
async function cancelRequest(id){if(!confirm('確定要取消這筆委託嗎？'))return;showLoading(true);try{await api('cancel_request',{id});await loadMine(false);renderFriend();toast('委託已取消')}catch(e){toast(e.message)}finally{showLoading(false)}}
async function copyPersonalUrl(){try{await navigator.clipboard.writeText($('personalUrl').value);toast('專屬連結已複製')}catch(_){$('personalUrl').select();document.execCommand('copy');toast('專屬連結已複製')}}

async function loadAdmin(repaint=true){const d=await api('admin_dashboard');app.people=d.people||[];app.requests=d.requests||[];applySettings(d.settings);if(repaint)renderAdmin()}
function renderAdmin(){const active=payableRequests(app.requests);const actual=active.reduce((s,r)=>s+Number(r.actual_yen||0),0);$('adminStats').innerHTML=`<div class="stat"><small>朋友人數</small><b>${app.people.length}</b></div><div class="stat"><small>全部委託</small><b>${app.requests.length}</b></div><div class="stat"><small>待採買</small><b>${active.filter(r=>!['已買到','待結算','已付款','已交付'].includes(r.status)).length}</b></div><div class="stat"><small>目前實付</small><b>${yen(actual)}</b><span class="tiny muted">≈ ${twd(actual*rate())}</span></div>`;renderAdminRecent();renderOrders();renderShopBoard();renderPeople();fillSettings()}
function adminRequestCard(r){const p=personName(r.person_id);const img=r.image_url?`<img class="thumb" src="${esc(r.image_url)}" alt="商品圖">`:`<div class="thumb empty">🛍️</div>`;return `<div class="request-card">${img}<div><h3>${esc(r.product_name)} ×${r.qty}</h3><div class="meta">${esc(p)} · ${esc(r.store_name||'店家待確認')} · ${esc(r.spec||'規格未填')}</div><div style="margin-top:8px">${badge(r.status)}</div></div><div class="money"><b>${r.actual_yen?yen(r.actual_yen):'待確認'}</b><span>${r.actual_yen?`≈ ${twd(requestTwd(r))}`:'尚未輸入實付'}</span></div></div>`}
function renderAdminRecent(){$('adminRecent').innerHTML=app.requests.length?app.requests.slice(0,5).map(adminRequestCard).join(''):`<div class="empty-state">還沒有朋友送出委託。</div>`}
function renderOrders(){const body=$('ordersBody');body.innerHTML=app.requests.map(r=>`<tr><td>${r.image_url?`<img class="table-thumb" src="${esc(r.image_url)}" alt="${esc(r.product_name)}" loading="lazy">`:`<div class="table-thumb empty">🛍️</div>`}</td><td><b>${esc(personName(r.person_id))}</b></td><td>${esc(r.product_name)} ×${r.qty}<div class="tiny muted">${esc(r.spec||'')}</div></td><td><input id="store-${r.id}" value="${esc(r.store_name||'')}"></td><td><select id="status-${r.id}">${STATUS.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></td><td><input id="est-${r.id}" type="number" min="0" value="${r.estimated_yen||0}"></td><td><input id="actual-${r.id}" type="number" min="0" value="${r.actual_yen||0}"></td><td>${r.actual_yen?twd(requestTwd(r)):'—'}</td><td><button class="btn green small" onclick="saveAdminRequest('${r.id}')">儲存</button></td></tr>`).join('')||`<tr><td colspan="9" class="muted" style="text-align:center;padding:30px">目前沒有委託</td></tr>`}
async function saveAdminRequest(id){showLoading(true);try{await api('admin_update_request',{id,store_name:$(`store-${id}`).value,status:$(`status-${id}`).value,estimated_yen:Number($(`est-${id}`).value||0),actual_yen:Number($(`actual-${id}`).value||0)});await loadAdmin(false);renderAdmin();toast('已更新')}catch(e){toast(e.message)}finally{showLoading(false)}}
function renderShopBoard(){const active=app.requests.filter(r=>!['已取消','跳過'].includes(r.status));const stores={};for(const r of active){const s=r.store_name||'店家待確認';(stores[s]??=[]).push(r)}const entries=Object.entries(stores);$('shopBoard').innerHTML=entries.length?entries.map(([store,rows])=>{const groups={};for(const r of rows){const k=`${r.product_name}||${r.spec||''}`;(groups[k]??={name:r.product_name,spec:r.spec||'',qty:0,rows:[],image_url:null});groups[k].qty+=Number(r.qty||0);groups[k].rows.push(r);if(!groups[k].image_url&&r.image_url)groups[k].image_url=r.image_url}return `<div class="shop"><div class="shop-top"><h3>📍 ${esc(store)}</h3><span class="count">${rows.filter(r=>!['已買到','待結算','已付款','已交付'].includes(r.status)).length} 件待處理</span></div>${Object.values(groups).map(g=>`<div class="agg"><div class="agg-line"><div class="agg-product">${g.image_url?`<img class="board-thumb" src="${esc(g.image_url)}" alt="${esc(g.name)}" loading="lazy">`:`<div class="board-thumb empty">🛍️</div>`}<div><b>${esc(g.name)} ×${g.qty}</b><div class="tiny muted">${esc(g.spec||'未填規格')}</div></div></div><button class="btn line small" onclick='markGroupPurchased(${JSON.stringify(g.rows.map(r=>r.id))})'>全標買到</button></div><div class="people-chips">${g.rows.map(r=>`<span class="chip">${esc(personName(r.person_id))} ×${r.qty} · ${esc(r.status)}</span>`).join('')}</div></div>`).join('')}</div>`}).join(''):`<div class="empty-state" style="grid-column:1/-1">目前沒有採買項目。</div>`}
async function markGroupPurchased(ids){if(!confirm('將這組商品全部標記為「已買到」？'))return;showLoading(true);try{for(const id of ids)await api('admin_update_request',{id,status:'已買到'});await loadAdmin(false);renderAdmin();toast('已全部標記為買到')}catch(e){toast(e.message)}finally{showLoading(false)}}
function renderPeople(){const grid=$('peopleGrid');grid.innerHTML=app.people.length?app.people.map(p=>{const rows=payableRequests(app.requests.filter(r=>r.person_id===p.id));const y=rows.reduce((s,r)=>s+Number(r.actual_yen||0),0);return `<div class="person"><h3>${esc(p.display_name)}</h3><div class="meta">LINE：${esc(p.line_name||'未填')}<br>專屬 ID：${esc(p.public_id)}<br>委託 ${rows.length} 筆</div><div class="person-total"><span>目前實付</span><div style="text-align:right"><b>${yen(y)}</b><div class="tiny muted">≈ ${twd(y*rate())}</div></div></div></div>`}).join(''):`<div class="empty-state" style="grid-column:1/-1">還沒有朋友建立身分。</div>`}
function fillSettings(){const s=app.settings||{};$('sTrip').value=s.trip_name||'';$('sRoute').value=s.route_note||'';$('sCutoff').value=s.order_cutoff||'';$('sRate').value=s.exchange_rate||0.22;$('sOpen').checked=!!s.registration_open}
async function saveSettings(){showLoading(true);try{const d=await api('admin_update_settings',{trip_name:$('sTrip').value,route_note:$('sRoute').value,order_cutoff:$('sCutoff').value,exchange_rate:Number($('sRate').value),registration_open:$('sOpen').checked});applySettings(d.settings);app.settings=d.settings;renderAdmin();toast('設定已儲存')}catch(e){toast(e.message)}finally{showLoading(false)}}
async function changeAdminPassword(){const current=$('currentAdminPassword').value;const next=$('newAdminPassword').value;const confirmNext=$('confirmAdminPassword').value;if(!current)return toast('請輸入目前的管理員密碼');if(next.length<8)return toast('新密碼至少需要 8 個字元');if(next!==confirmNext)return toast('兩次輸入的新密碼不一致');if(!confirm('修改後會登出所有管理員裝置，確定繼續？'))return;showLoading(true);try{await api('admin_change_password',{current_password:current,new_password:next});$('currentAdminPassword').value='';$('newAdminPassword').value='';$('confirmAdminPassword').value='';setSession('',null);app.role=null;app.person=null;app.requests=[];app.people=[];showGuest();switchAuth('admin');$('adminPassword').value='';scrollAuth();toast('密碼已更新，請用新密碼重新登入')}catch(e){toast(e.message)}finally{showLoading(false)}}
async function copyMainUrl(){try{await navigator.clipboard.writeText($('mainShareUrl').value);toast('朋友登記網址已複製')}catch(_){$('mainShareUrl').select();document.execCommand('copy');toast('網址已複製')}}

window.addEventListener('load',init);